version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - spiderweb

  consumer:
    build: ./consumer
    environment:
      - RABBIT_MQ_HOST=rabbitmq
      - RABBITMQ_USER=rmuser
      - RABBITMQ_PASS=rmpassword
      - QUEUE_NAME=meassages
    depends_on:
      - rabbitmq
    networks:
      - spiderweb
    restart: always
    deploy:
      replicas: 2

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    environment:
      - RABBIT_MQ_HOST=rabbitmq
      - RABBITMQ_USER=rmuser
      - RABBITMQ_PASS=rmpassword
      - QUEUE_NAME=meassages
    scale: 1
    networks:
      - spiderweb
      
networks:
  spiderweb:
    driver: bridge
# links, depends_on

volumes:
  db-data:

