apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    type: Recreate
  template: 
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.10.7-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: rmuser
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: mq-password
              key: password
        - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
          value: -rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
        ports:
        - containerPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: api
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: dashboardapi
  selector:
    app: rabbitmq